name: link_shortener
description: A simple link shortener.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  bloc: ^8.0.2
  equatable_stack:
    path: packages/equatable_stack
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  url_shortener_api:
    path: packages/url_shortener_api
  url_shortener_repository:
    path: packages/url_shortener_repository

dev_dependencies:
  bloc_test: ^9.0.2
  build_runner: ^2.1.7
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  mocktail: ^0.2.0
  test: ^1.19.5
  very_good_analysis: ^2.4.0

flutter:
  uses-material-design: true
  generate: true
flutter_intl:
  enabled: true